os:
  - linux
  - osx
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
  - '10'
env:
  - IOBROKER=master
  - IOBROKER=1.5.x
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm@5; fi'
  - npm -v
  - npm install winston@2.3.1
  - 'if [ "$IOBROKER" == "master" ]; then npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production; fi'
  - 'if [ "$IOBROKER" == "1.5.x" ]; then npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/${IOBROKER} --production; fi'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
- g++-4.8
